README.md
Somehow omitting `@main` from the `uses` statement makes the reference to the Action invalid as I learned in the [Z2N repo](https://github.com/determinatesystems/zero-to-nix):
https://github.com/DeterminateSystems/zero-to-nix/actions/runs/3940423934
Apparently it needs to be a Docker image, a path, or `{owner}/{repo}@{ref}`.
=> Update README example `uses` statement

action.yml
Be more clever with situations where the user may already have Nix installed (via this action) from previous runs.
This is relevant because private runners can be configured to have some manner of persistence where desired.
=> Better handle gha runners with persistence

action.yml
Since you are likely to be rate-limited if you use this action
without a GitHub API token, default the action's `github-token` input
to the `token` from the `github` context[^1].
Closes #3
[^1]: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
=> Add default value for the the github-token input

.github/workflows/ci.yml, README.md
Follows up on https://github.com/DeterminateSystems/nix-installer-action/pull/6#issuecomment-1412552331
=> Use github token from context not secret

.github/workflows/ci.yml, action.yml
Usually we want the runner user to be able to configure binary caches.
=> Make the runner user trusted by default

action.yml
Some Mac options required users to actually manually select that planner.
We can improve this later, but for now, this is necessary.
=> Clarify options which require a specific planner

action.yml
I was writing up a Markdown table for the configurable parameters and noticed that this is misnamed in the script.
=> Fix input parameter name for user count

action.yml
Add a `?ci=github` to our auto generated URLs. This will allow us to provide Github Actions with binaries which may be slightly more recent than normal requests, since Github Actions exist within a much more controlled environment.
=> Add a ?ci=github to GHA requests

src/main.ts
* the use of `else if` would have made the "counting" of the url modifiers useless, so switch them to ifs.
* correspondingly, update the fallthrough `else` condition to set the URL if no modifiers were passed to override it
=> main.ts: fixup logic to ensure only one installer url override is set

.github/workflows/ci.yml
The Magic Nix Cache isn't really necessary in the test suite so we're removing it, as reinstalling Nix wipes out the Nix store and thus the MNC executable. It'd be nice to concoct a nice way to test these two things side by side but that's an exercise best left for a future day.
=> Fix broken CI caused by Nix reinstallation wiping out the Magic Nix Cache

.editorconfig, .github/verify-version.sh, .github/workflows/ci.yml, action.yml
Fixes #84.
Updates the misleading `action.yml` description and also adds a basic GHA workflow for a handful of non-default `source-*` inputs.
=> Update action.yml description for source-url

.github/workflows/ci.yml
Somehow #89 got merged despite failing CI jobs. This PR fixes that.
=> Provide new test matrix for source-* inputs

action.yml, dist/index.js, src/index.ts
=> Disable docker under act

.github/workflows/ci.yml
GitHub Actions considers a "skipped" job successful for the purposes of required jobs for branch protections. We take advantage of this by failing if any dependent actions failed, or "skip" if they all succeeded.
=> tests: make megajob block on failure

dist/index.js, package.json, pnpm-lock.yaml, src/index.ts
Some executions are failing to connect to our backend systems on Fly.io. This PR lets us probe access to backend domains and measure the results across a wide variety of environments.
=> science: probes to debug fly on GHA

dist/index.js, src/index.ts
Namespace's x86 runners don't work correctly without /lib64 for /bin/sh.
I suspect the additional care around directory mounting will reduce the failures in act, too.
=> Share /lib64 into the container

dist/index.js, src/index.ts
Log in to FlakeHub when a machine has persistent storage between runs.
=> Log in to flakehub on existing installs

dist/index.js, src/failuresummary.test.ts, src/failuresummary.ts
In https://github.com/DeterminateSystems/nixos-vault-service/actions/runs/14625223942 we got an error:
> $GITHUB_STEP_SUMMARY upload aborted, supports content up to a size of 1024k, got 1063k. For more information see: https://docs.github.com/actions/using-workflows/workflow-commands-for-github-actions#adding-a-markdown-summary
This PR clamps the length to a displayable limit, and shows the user how to see the logs anyway.
 
It now looks like this if the log is too large:
> ### Build error review :boom:
> > [!NOTE]
> > 2 builds failed
> <details><summary>Failure log: <code>/nix/store/rz9hrpay90sjrid5hx3x8v606ji679xa-<strong>dep-1</strong>.drv</code></summary>
> 
>     /nix/store/rz9hrpay90sjrid5hx3x8v606ji679xa-dep-1.drv
>     /nix/store/rz9hrpay90sjrid5hx3x8v606ji679xa-dep-1.drv
> …
=> Don't blow the limits of summaries, by not printing logs if it blows the limit

CONTRIBUTING.md, dist/index.js, src/index.ts
=> chore: detect existing `nix` installations

dist/index.js, src/index.ts
I've recently started using this action with a runner using [act](https://github.com/nektos/act), which uses docker containers to provide the standard actions environments (such as `ubuntu-latest`). I'd like to use this action to install nix with kvm enabled, but currently the KVM setup fails due to udev not being installed in the docker container.
KVM is already fully functional inside the container (I've passed `/dev/kvm` to the docker container and added the runner user to the `kvm` group), so installing udev and modifying rules is unnecessary.
This PR checks whether KVM is available to the current user, and if it is then it skips setting up udev rules.
=> Check whether the current user has access to KVM before attempting to add udev rule

dist/index.js, src/mermaid.ts
For some reason, TypeScript didn't catch this: `string` and `undefined` shouldn't be comparable since they have no overlapping types.
I've chosen to just use the short-cut falsy check here to avoid future complications.
=> Correctly suppress empty summaries

src/mermaid.test.ts
This PR cleans up the Mermaid tests:
1. It adds a test that should've been part of #171, and
2. It removes some unneeded nested blocks.
=> Test penance

dist/index.js, src/failuresummary.test.ts, src/failuresummary.ts, src/mermaid.test.ts, src/mermaid.ts
https://github.com/DeterminateSystems/docs.determinate.systems/actions/runs/14893979984/attempts/1#summary-41832596554
first, long jobs are showing thousands of seconds in the graph,
and there is a double NOTE:
> [!NOTE]
> 1 build failed
> [!NOTE]
> The following failure has been ommitted due to GitHub Actions summary length limitations.
> The full logs are available in the post-run phase of the Nix Installer Action.
/nix/store/m7gxzgk460q28z52xh211r0gwvz4ak24-nodejs-20.19.0.drv
=> Fix an obscure error case where if the only log fails, the rendering is wack
