- action.yml
Goes along with https://github.com/DeterminateSystems/nix-installer/pull/188
> Add start-daemon and init args

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Closes https://github.com/DeterminateSystems/nix-installer-action/issues/15.
> README: use tagged release

- action.yml
https://github.com/DeterminateSystems/nix-installer/pull/304
> Reflect removal of channels in upcoming version

- .github/workflows/ci.yml
- action.yml
Fixes https://github.com/DeterminateSystems/nix-installer-action/issues/21 (probably)
> v0.9.0 - nix profile location change

- .github/workflows/ci.yml
Maybe we can use hello instead!
> In GHA use Hello instead of fortune

- README.md
Updates the README's usage example to reflect latest `v3` release of the action.
- (N/A) Tested changes against a test repository
> Update example in README to use v3

- .github/workflows/ci.yml
- action.yml
> Add act support

- action.yml
> --nix-build-user-base and --nix-build-user-prefix logic no longer confused

- action.yml
- flake.lock
- flake.nix
> Update the action to use node20

- .github/workflows/ci.yml
Used this in my fork to test changes to the other two PRs I'm sending. Nice convenience.
> .github: allow trigger ci manually

- .github/workflows/ci.yml
- CONTRIBUTING.md
I noticed in #47 we should document and check this.
> Add check for dist folder

- dist/index.js
- dist/main.js
- src/main.ts
* https://github.com/DeterminateSystems/nix-installer/actions/runs/8804671317/job/24165542506?pr=917
> Gracefully handle FlakeHub login failure

- .eslintrc.json
- .github/workflows/ci.yml
- dist/index.js
- dist/main.js
- package.json
- pnpm-lock.yaml
- src/main.ts
This PR adds some quality of life improvements and enforces some best practices, such as:
- Proper casing for names
- Heavier use of `detsys-ts`
- Making some things `const`
> General JS cleanup

- .github/workflows/ci.yml
- README.md
> Standardize on v4 of the checkout action

- dist/index.js
- pnpm-lock.yaml
- src/index.ts
- tsup.config.ts
Reverts DeterminateSystems/nix-installer-action#83
> Revert "Fix ESM build"

- .eslintrc.json
- action.yml
- dist/index.js
- package.json
- pnpm-lock.yaml
- src/index.ts
> Srv update

- .github/workflows/ci.yml
- dist/index.js
- src/index.ts
> Log in to flakehub for 'fh' too

- dist/index.js
- src/index.ts
> fixup extra arguments

- package.json
- pnpm-lock.yaml
> Update @actions/github to 6.0.0

- .github/workflows/ci.yml
> fail-fast: false

- dist/index.js
- package.json
- pnpm-lock.yaml
- src/events.test.ts
- src/events.ts
- src/failuresummary.test.ts
- src/failuresummary.ts
- src/fixHashes.ts
- src/index.ts
- src/mermaid.test.ts
- src/mermaid.ts
- src/util.ts
- tsconfig.json
ref https://linear.app/detsys/issue/FH-703/delighter-summarize-build-failures-and-timeline-in-gha
> Summarize the build timeline

- dist/index.js
- src/index.ts
This PR adds some diagnostic information if the action cannot log in to FlakeHub. We specifically check two cases:
* A pull request introduced from a forked repository,
* `id-token: write` is missing from the job's permissions.
> Show diagnostics for FlakeHub login issues

- dist/index.js
- src/index.ts
> Sometimes, two heads are NOT as good as one.

- dist/index.js
- src/events.test.ts
- src/events.ts
- src/index.ts
- src/mermaid.test.ts
This PR adds a notice if hash mismatches were encountered during the build.
> Add hash mismatches to summary

- README.md
> Add a note about pinning
